title: Redonda 
description: Toward A Next-Generation State-Machine Replication Protocol for Blockchain.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:  
# - jekyll-remote-theme # add this line to the plugins list if you already have one
